### ISSUE TITLE
Стейкхолдеры и методика

### ISSUE THREAD

**Issue by olgapshen** [NorthGateVologda/NorthGate#10]
Пообщаться со стейкхолдерами по методике выбора объекта торговли

**Comment by Marwin887** [comment]
Методика: 

1. Определить категории объектов, которые нужно разместить или модернизировать в арктических городах. Для этой цели необходимо проанализировать данные по городам Арктической зоны (в рамках MVP это г. Архангельск), через индекс качества жизни в городах России  https://citylifeindex.ru/city_profile/Arhangelsk путем сопоставления с городами куда идет основной миграционный отток населения. 
2. Определить параметры индекса,  которые можно изменить путем размещения новых и(или) модернизации существующих городских объектов.
3. Определить соотношение п1. и п2. и проранжировать от самого низкого значения (не дотягивает до сравниваемых городов) до самого высокого показателя. 
4. Проанализировать наборы собранных данных на предмет того размещения каких объектов из каких категорий можно спрогнозировать.
5. Прогноз размещения "ПАРКОВ"
6. Прогноз размещения объектов "Здравохранения"

**Comment by olgapshen** [comment]
Коллеги, не забывайте пожалуйста обновлять статус :)
![изображение](https://github.com/NorthGateVologda/NorthGate/assets/13800244/d3a2eb63-7880-4090-9e36-9a732e97137a)

**Comment by olgapshen** [comment]
Ребята, актуализируйте пожалуйста задачи :)

**Comment by olgapshen** [comment]
Слилось с данной задачей: [Написать User Story](https://github.com/NorthGateVologda/NorthGate/issues/5)
