### ISSUE TITLE
Изучить имеющиеся датасеты

### ISSUE THREAD

**Issue by olgapshen** [NorthGateVologda/NorthGate#11]
Изучить имеющиеся датасеты

* Что там есть
* Применимость к юзерстори

**Comment by Marwin887** [comment]
Перечень источников данных зафиксирован в файле https://docs.google.com/spreadsheets/d/1MwbBHrDEjvD7Pb5jlaO7rQxmWyK6RTUk6IXwcGUjEbk/edit?usp=sharing 
-Необходимо добавить данные о наличии API для выгрузки и формат получения данных;
-Необходимо добавить описание структуры данных;
-Необходимо добавить описание формата к которому необходимо привести данные для дальнейшего использования в рамках MVP;

**Comment by olgapshen** [comment]
> Необходимо добавить данные о наличии API для выгрузки и формат получения данных;

Перенесла вкладку API из "Ресурсов" в "Источники данных"

**Comment by olgapshen** [comment]
Тут у нас какой статус?

**Comment by olgapshen** [comment]
Ладно, тут достаточная степень проработки. Я в файле Источники данных ещё добавила колонку "Комментарий", там в одном месте битая ссылка есть.
