### ISSUE TITLE
Разбить данные по репозиториям

### ISSUE THREAD

**Issue by olgapshen** [NorthGateVologda/NorthGate#14]
Сейчас у нас есть два репозитрия:

* [Общий](https://github.com/NorthGateVologda/NorthGate)
* [Метаданные ГитХаба](https://github.com/NorthGateVologda/.github)

Метаданные оставляем, и по необходимости обогащаем.
Основной оставляем пока для поступающих, не классифицированных и исследовательских кодов.

- [x] Из основного выделить отдельный репозиторий wiki
- [x] Добавить wiki папку для uml-ек и папку для сегенрированных из uml svg-шек
- [x] Добавить svg-шки в markdown файлы в репозитории wiki
- [x] Научиться генерировать uml-ки из Visual Studio Code
- [x] Добавить репозиторий swarm для данных по Docker-у
- [x] Залить туда все файлы по нашей Docker инфраструктуре
- [x] Отдельный репозиторий для бекенда

**Comment by olgapshen** [comment]
Тёма, делигируй!

**Comment by sshiae** [comment]
Как вариант можно отдельно для бекенда, тут уже вопрос удобства

**Comment by olgapshen** [comment]
> Как вариант можно отдельно для бекенда, тут уже вопрос удобства

Давай отдельный репозиторий для бекенда.

**Comment by sshiae** [comment]
UML в Visual Studio Code создается с помощью плагина `PlantUML`, после этого нужно создать файл с расширением `.wsd`, в ней можно писать UML код, для генерации `SVG` необходимо в `UML файле`  нажать правой кнопкой мыши и выбрать `Export Current Diagram`
