### ISSUE TITLE
Интегрировать Datalense с API

### ISSUE THREAD

**Issue by olgapshen** [NorthGateVologda/NorthGate#17]
С функцией вот от [сюда](https://github.com/NorthGateVologda/NorthGateBackend/issues/2)

**Comment by olgapshen** [comment]
Тёма, делигируй!

**Comment by sshiae** [comment]
После выполнения задачи по подтягиванию данных из базы данных с помощью `Python` и создание `API` для получения этих данных, необходимо созданную `API` интегрировать с `Yandex DataLense`.

**Comment by sshiae** [comment]
Что по этой задаче делаем? Закрываем?

**Comment by olgapshen** [comment]
> Что по этой задаче делаем? Закрываем?

Так появился то у нас API с интерфейсом и выводом в Datalens?

**Comment by olgapshen** [comment]
Всё, замечательно! Можно закрывать :)
