### ISSUE TITLE
Сконвертировать из GeoJSON в DataLense CSV

### ISSUE THREAD

**Issue by olgapshen** [NorthGateVologda/NorthGate#2]
Перевести все датасеты которые хранятся на Google диске в формат читаемый сервисом DataLense

- [x] arhangelskaya_oblast.geojson
- [x] auto_foot_graph_arh_obl.geojson
- [x] base_obl_people.geojson
- [x] base_obl_people_3000.geojson
- [x] buildings.geojson
- [x] mun_obr_all_bad.geojson
- [x] mun_obr_arctic.geojson
- [x] objects_education.geojson
- [x] objects_tourism.geojson
- [x] objects_zdrav.geojson
- [x] slow_roads_lines.geojson

**Comment by Marwin887** [comment]
[slow_roads_lines.csv](https://github.com/NorthGateVologda/NorthGate/files/11844311/slow_roads_lines.csv)
[arhangelskaya_oblast.csv](https://github.com/NorthGateVologda/NorthGate/files/11844310/arhangelskaya_oblast.csv)
[base_obl_people.csv](https://github.com/NorthGateVologda/NorthGate/files/11844312/base_obl_people.csv)
[base_obl_people_3000.csv](https://github.com/NorthGateVologda/NorthGate/files/11844317/base_obl_people_3000.csv)
[buildings.csv](https://github.com/NorthGateVologda/NorthGate/files/11844313/buildings.csv)
[mun_obr_all_bad.csv](https://github.com/NorthGateVologda/NorthGate/files/11844319/mun_obr_all_bad.csv)
[mun_obr_arctic.csv](https://github.com/NorthGateVologda/NorthGate/files/11844318/mun_obr_arctic.csv)
[objects_education.csv](https://github.com/NorthGateVologda/NorthGate/files/11844315/objects_education.csv)
[objects_tourism.csv](https://github.com/NorthGateVologda/NorthGate/files/11844314/objects_tourism.csv)
[objects_zdrav.csv](https://github.com/NorthGateVologda/NorthGate/files/11844316/objects_zdrav.csv)

**Comment by Marwin887** [comment]
Оля, залил все в CSV, но при конвертации потерял [], и не смок сконвертировать файл на 65 mb

**Comment by olgapshen** [comment]
Ага! Спасибо :) как будет база залью. Но думаю, что Миша уже может начать играться с этими файлами в Exce-е

**Comment by Marwin887** [comment]
@olgapshen Оля, я бы поигрался если бы данные вставали корректно как гео-точки и гео-полигоны.  Вот тут нужна твоя помощь.

**Comment by olgapshen** [comment]
Сейчас попробую.

**Comment by olgapshen** [comment]
Хочу сразу набить руку в Yandex DataSphere, попробовала создать Jupiter Notebook (для трансформации данных) в твоей организации: org-marwin887, сказали нет прав. Что бы не тормошить тебя постоянно с правами, создам у себя: org-yaolgapshenichnikova :) Отправила тебе приглашение.

**Comment by Marwin887** [comment]
@olgapshen Принял, как будут готовы данные напиши. Только я не знаю как из Datasphere пердать их в Datalens. Можно попробовать череp object storgate

**Comment by olgapshen** [comment]
Хитрый Яндекс снова запросил платёжную карту, так что я делаю в Jupiter-е у себя. Сейчас будет CSV дорог. Я загружу на Google Disk

**Comment by olgapshen** [comment]
Загрузила на Google диск в папку Арктика/Датасеты файл данных auto_foot_graph_arh_obl.csv. Соответственно данные это auto_foot_graph_arh_obl.json по дорогам.
Вот тут детали конвертирования: https://github.com/NorthGateVologda/NorthGate/blob/main/GeoJSON.ipynb

**Comment by olgapshen** [comment]
![изображение](https://github.com/NorthGateVologda/NorthGate/assets/13800244/c318d610-8e0b-4957-96fd-edbf2109e1bb)

**Comment by olgapshen** [comment]
@sshiae Добавлю сюда Тёму, так как он поднимает базу для этих данных.

**Comment by Marwin887** [comment]
@olgapshen Оля, привет помучался с файлом, который мы конвертируем. Datalens не видит координаты которые есть, причина скорее всего в разных форматах, подробнее описано https://cloud.yandex.ru/docs/datalens/function-ref/GEOPOINT  и  https://cloud.yandex.ru/docs/datalens/function-ref/GEOPOLYGON, а в тех данных которые нам дали там не координаты широта и долгота в формате 55.79421,37.65046, а что-то другое. Я скачал QGIS он без труда распознал файл Auto_Foo_graph_arh.....
![image](https://github.com/NorthGateVologda/NorthGate/assets/136377502/42aa19f9-72a2-47e6-8006-0a3988f23c88)
Ломаю голову как  4535921.132800005376339, 9456698.171899996697903 привезти к формату 55.79421,37.65046

**Comment by Marwin887** [comment]
вот в принципе нужный нам формат указан  второй строчкой 
![image](https://github.com/NorthGateVologda/NorthGate/assets/136377502/3e65e575-0645-405d-89fc-9f2301e04723)

**Comment by Marwin887** [comment]
Вот оля тут конверторами побаловался нашел название из чего в чего нужно перевести 
![image](https://github.com/NorthGateVologda/NorthGate/assets/136377502/8ee99bb3-ed77-4db4-bafc-3ad26bdf8f35)

**Comment by sshiae** [comment]
Ребят, на счет настройки инфраструктуры и базы данных отписал в другой задаче: [Поднятие PostgreSQL](https://github.com/NorthGateVologda/NorthGate/issues/3#issuecomment-1606143998)

**Comment by olgapshen** [comment]
> @olgapshen Оля, привет помучался с файлом, который мы конвертируем. Datalens не видит координаты которые есть, причина скорее всего в разных форматах, подробнее описано https://cloud.yandex.ru/docs/datalens/function-ref/GEOPOINT и https://cloud.yandex.ru/docs/datalens/function-ref/GEOPOLYGON, а в тех данных которые нам дали там не координаты широта и долгота в формате 55.79421,37.65046, а что-то другое. Я скачал QGIS он без труда распознал файл Auto_Foo_graph_arh..... 
Ломаю голову как 4535921.132800005376339, 9456698.171899996697903 привезти к формату 55.79421,37.65046

Кстати где то писалось, что система координат относительная. Хотела уточнить, QGIS читает .geojson или .csv которые сконвертировали? И какая сейчас ситуация по загрузке данных?

**Comment by olgapshen** [comment]
> Вот оля тут конверторами побаловался нашел название из чего в чего нужно перевести

Так, сегодня изучала эту тему. Для меня это тоже всё новое, вот [небольшое исследование от меня](https://github.com/NorthGateVologda/NorthGate/blob/main/wiki/CRS.md)

Завтра переведу данные в нужную систему координат. Это всё часть библиотеки `geopandas`

**Comment by olgapshen** [comment]
Так, всё готово, те файлы список которых в начале, которые лежали в корне папки я перевела.
Вижу добавились ещё файлы. Нужно подумать теперь о методике перевода и главное о том, куда мы эти данные и каким образом будем складывать.
Нужно решить что мы делаем дальше по теме интеграции данных.
![изображение](https://github.com/NorthGateVologda/NorthGate/assets/13800244/bdf4fc92-bcf1-4080-89b2-0c98938bcd89)
