### ISSUE TITLE
Первая магия

### ISSUE THREAD

**Issue by olgapshen** [NorthGateVologda/NorthGate#20]
В продолжении совещания прошедшего сегодня в обед, расписываю первую модель, которую необходимо построить к 4-ому июля.

* Все поля добавляем в базу
* Создать градиенты плотности населения в Архангельске
  * Основываемся на наборе данных постройки
    * Добавляем поле количества жильцов дома
      * Основываемся на годе постройки
        * До определённого года считаем одну среднюю после другую
        * В идеале грузим данные из Росреестра
* Создаём заданные полигоны вокруг точек инфраструктуры
  * Выгружаем данные из набора данных по инфраструктуре
  * К каждому объекту добавляем поля
    * Норматив обслуживаемого количества населения
    * Радиус окружности охвата данного объекта
* Считаем количество населения в полигонах
* Выводим к каждому объекту информацию по избытку населений
  * В виде силы заданного цвета, к примеру оттенками красного
  * Лейбочками с разницей

**Comment by olgapshen** [comment]
@lvapl ты наверное по ошибке эту задачу в Done перевёл... Так то я только что её закончила :)

**Comment by lvapl** [comment]
Я с телефона сижу, случайно задел задачу видимо

**Comment by olgapshen** [comment]
Итак.

* [Notebook](https://github.com/NorthGateVologda/NorthGate/blob/main/Notebooks/FirstMagic.ipynb)
* [Datasphere](https://datasphere.yandex.ru/communities/bt16mjs3iif0mdb2ranv/projects/bt1adl946ond8anb5h9t/jupyterlab)
* [Datalens](https://datalens.yandex.ru/wizard/kbhbfmsp9ykq9-people-medicin-map)

Буфер в базе:

![изображение](https://github.com/NorthGateVologda/NorthGate/assets/13800244/84ee8902-1140-419a-9ab1-2771bbe22143)

Вот так это выглядит в Datalens:

![изображение](https://github.com/NorthGateVologda/NorthGate/assets/13800244/cd7bba7e-2049-4ee1-9202-986e07f59df8)

**Comment by olgapshen** [comment]
Вот теперь можно закрывать :)
