### ISSUE TITLE
Описание метода расчета плотности населения

### ISSUE THREAD

**Issue by Malaxov16** [NorthGateVologda/NorthGate#26]

**Comment by Malaxov16** [comment]
Источники данных для расчета плотности населения:

- Датасет buildings.geojson: https://drive.google.com/file/d/1ueVGpQ-3Kpjx38kF-JlEU6seTpezJp9C/view?usp=drive_link
- Реестр домов по Архангельской области: https://аис.фрт.рф/opendata?gid=2216073&cids=house_management&page=1&pageSize=12

Рассматриваемый населенный пункт г. Архангельск.  
Данные источников о количестве домов отличаются. Так в датасете список содержит **9600** строк, в реестре домов **4345** строк. На текущий момент для расчетов используется источник с реестром домов, т.к. содержит более полную информацию.  
!!!В дальнейшем необходимо проработать вопрос о корректности данных источников.

**Comment by olgapshen** [comment]
[Связанная задача](https://github.com/NorthGateVologda/NorthGate/issues/30)

**Comment by olgapshen** [comment]
Вы занесли то всё в документацию?
