### ISSUE TITLE
Описание метода расчета индекса объектов "Парк"

### ISSUE THREAD

**Issue by Malaxov16** [NorthGateVologda/NorthGate#28]

**Comment by Malaxov16** [comment]
1). Рассчитать парковую площадь в городах, в которые выезжает население. N кв.м. на человека принять за эталон.
2). Принять за эталон 15 минутную доступность парка не зависимо от населения.

**Comment by olgapshen** [comment]
[Связанная задача](https://github.com/NorthGateVologda/NorthGate/issues/31)

**Comment by olgapshen** [comment]
Вы занесли то всё в документацию?

**Comment by olgapshen** [comment]
Архивирую задачу. Если что задача тут:


![Image](https://github.com/NorthGateVologda/NorthGate/assets/13800244/2de28e6b-0509-4734-b37e-6cea0210054a)
