### ISSUE TITLE
Парсинг данных из 2GIS

### ISSUE THREAD

**Issue by Malaxov16** [NorthGateVologda/NorthGate#35]
Спарсить данные из 2GIS,необходимые для расчета обеспеченности объектами типа "Парк".

Задача с описанием методики расчета обеспеченности https://github.com/NorthGateVologda/NorthGate/issues/28

Дополнительно можно посмотреть тему с экспортом объектов из Яндекс карт. Предположительно, есть такой способ https://yandex.ru/support/maps-builder/concept/markers_3.html

**Comment by Malaxov16** [comment]
Спарсил рестораны и кафе 

[arkh_eat.csv.xlsx](https://github.com/NorthGateVologda/NorthGate/files/12136820/arkh_eat.csv.xlsx)

**Comment by olgapshen** [comment]
Залей всю информацию в базу.... Сможешь?

**Comment by Marwin887** [comment]
@olgapshen Оля, данные все спарсили. закачал в БД в таблицу Facility, все кроме мест парковок. Парковки сегодня закачаю, тоже их нашел. Нужно довести столбец coordinates до ума, что бы у него был тип POINT. Резать отдельную задачу не вижу смысла.

**Comment by olgapshen** [comment]
Добавила в facility в колонку geometry координаты в формате geo postgis.

**Comment by olgapshen** [comment]
> 3). Объекты транспортной инфраструктуры (парковки, остановки) не удается спарсить. Остановки не парсятся, скорее всего имеют отличную от других объектов структуру представления. Парковок очень много, при парсинге более 100 строк 2GIS блокирует работу с сайтом, при прасинге небольшими участками карты парсинг может падать в ошибку.

Это всё надо грузить через Overpass или из nextgis, но единоразово через Nifi.

**Comment by olgapshen** [comment]
@Marwin887 Раз всё доступное залили можно закрывать?

**Comment by Marwin887** [comment]
@olgapshen Остановки я загрузил, задачу закрою
