### ISSUE TITLE
Контур обогащения из Росреестра

### ISSUE THREAD

**Issue by olgapshen** [NorthGateVologda/NorthGate#37]
Если успеем к данному Deadline-у, то можно сотворить очень крутую вещь которая даст бонус нашей системе, и она довольно таки не трудно реализуемая. К тому же у нас появится площадь домов. Так то мы и в ручную можем её загрузить, но с `Nifi` есть момент масштабируемости. В рамках задачи мы добавим функцию `Geocode` используя `Yandex API` у так у нас уже будут две функции:

* `GET addressByPoint (Point point) -> string address`
* `GET touristsObjects (Point point, real radius)`

Плюс ещё добавим пару, главное, чтобы тянулось через `Postman`.

Далее добавить в `Nifi` процессор на `API` и можно обогатить таблицу `api_houses`, затем из неё вывести плотность населения по существующей [матмодели](https://github.com/NorthGateVologda/NorthGate/blob/main/Notebooks/MedicalProficit.ipynb)

На всякий случай, вот наш [репозиторий](https://datasphere.yandex.ru/communities/bt16mjs3iif0mdb2ranv/projects/bt1adl946ond8anb5h9t) в `DataShpere`.

Вот [ссылка](https://аис.фрт.рф/opendata?gid=2216073&cids=house_management&page=1&pageSize=12) на `CSV`-шки из Росреестра.

Далее общая идея.

Сейчас процессоры грузят данные из таблицы в `buildings` в таблицу `api_houses`. В `api_houses` должна быть информация из зданий которые предоставили организаторы и из файлов из Росреестра с площадью. Но для обогащения из данных Росреестра нужна функция `API` проксирующая геокод.

Сюда

![Image](https://github.com/NorthGateVologda/NorthGate/assets/13800244/ae06cf58-14e2-4a8c-a6be-499beeef03e5)

От Сюда

![Image](https://github.com/NorthGateVologda/NorthGate/assets/13800244/7d947f17-0de4-436b-bf81-2e5be8c3e677)

```
id - serial
org_id - id из buildings
rr_id - RosReestr ID - id из CSV файлов Росреестра
geometry - точка из buildings
area - площадь из Росреестра
```

**Comment by Marwin887** [comment]
Тема не актуальна

**Comment by olgapshen** [comment]
Ну, на следующий этап так то актуальна :)
