### ISSUE TITLE
Добавить информацию о ДаДата в файл источников данных

### ISSUE THREAD

**Issue by olgapshen** [NorthGateVologda/NorthGate#39]
Добавить в закладку - API.
Пароль можно всем в личку.

**Comment by olgapshen** [comment]
Извиняюсь, не в файл ресурсов, а в файл [источников данных](https://docs.google.com/spreadsheets/d/1MwbBHrDEjvD7Pb5jlaO7rQxmWyK6RTUk6IXwcGUjEbk/edit#gid=627297237) закладка API

**Comment by olgapshen** [comment]
![Image](https://github.com/NorthGateVologda/NorthGate/assets/13800244/69163961-7f23-44a5-9d01-5b1a168589d0)

**Comment by Marwin887** [comment]
По итогу Дадату не использовали, сделали все через  API Яндекс
