### ISSUE TITLE
MVP кровь из носу

### ISSUE THREAD

**Issue by Marwin887** [NorthGateVologda/NorthGate#41]
- [x] @Malaxov16  Провести Геокодинг домов, не дожидаясь всех данных грузить X и Y в БД таблица house_ais. Андрей важно это нужно сделать как можно скорее.
- [x] @olgapshen @sshiae  Сформировать сетку полигонов и рассчитать количество пересечений в разрезе type точек из таблицы Facility. Сетку уже Оля делала для алко магазинов. Полигоны сетки нужно занести в БД. Для расчета у каждой точки  Facility нужно  проставить ID полигона. 
- [x] @olgapshen @sshiae e как только @Malaxov16  закончить геокодинг, нужно аналогично сделать для домов для каждого дома поставить ID полигона. Оля в таблице house_ais потребуется добавить Point как делали для Facility.. 
- [x] @olgapshen @sshiae  выбрать из реализованных 2-3 самых интересных API снять коротки ролик с их демонстрацией через POSTMAN, можно сразу с озвучкой. Если нет озвучки то текстом написать, я озвучу что происходит на видео. ВИДЕО максимум 1-1.5 минуты. Сформировать PDF c описание API для жюри, которое они могут сами запустить через POSTMAN (если один метод то тогда его)
- [x] @olgapshen @sshiae  текстом написать ответы на вопросы ниже
- [x] @Marwin887 сделать дашборд по паркам. актуализировать презентацию, отредактировать видео.

Вопросы для Оли:

1. 5 ключевых фичей, функций бэкенда и фронта,  которые нами реализованы в рамках проекта  и которые вас цепляют с позитивной стороны (на каждую фичу максимум 3 предложения)?
2. Описать текущею инфраструктуру MVP, актуализировать схему в MIRO и (5-6 пояснительных предложений)?
3. Как организаторам самим изучить наш БЭК и фронт?

**Comment by olgapshen** [comment]
> 5 ключевых фичей, функций бэкенда и фронта, которые нами реализованы в рамках проекта и которые вас цепляют с позитивной стороны (на каждую фичу максимум 3 предложения)?

Тут то Nifi можно вставить? :)

**Comment by olgapshen** [comment]
> Описать текущею инфраструктуру MVP, актуализировать схему в MIRO и (5-6 пояснительных предложений)?

https://github.com/NorthGateVologda/NorthGateWiki/blob/main/ARCHITECTURE.md

@sshiae Тём, актуализируй часть API backend-f, @lvapl актуализируй пожалуйста диаграмму фронтенда

**Comment by Marwin887** [comment]
> > 5 ключевых фичей, функций бэкенда и фронта, которые нами реализованы в рамках проекта и которые вас цепляют с позитивной стороны (на каждую фичу максимум 3 предложения)?
> 
> Тут то Nifi можно вставить? :)

Да можно

**Comment by olgapshen** [comment]
Прикреплю на всякий случай.
Связанная задача: https://github.com/NorthGateVologda/NorthGate/issues/36

**Comment by olgapshen** [comment]
@lvapl фронтенд то поднимем с какой нибудь новой фичей?

**Comment by lvapl** [comment]
Да, но я ещё доделываю

**Comment by olgapshen** [comment]
> Да, но я ещё доделываю

Возьми сегодня за свой счёт.. Вить... Тёма взял...

**Comment by lvapl** [comment]
У меня компьютер на даче, так что я лучше тут в свободное время от задач буду делать фротенд. Сегодня должен успеть

**Comment by olgapshen** [comment]
@Marwin887 по сетке с полигонами.
Вот [ноутбук](https://github.com/NorthGateVologda/NorthGate/blob/main/Notebooks/Facility.ipynb)

Если тема с дубликатами решена, сейчас пересоздам и всё залью.

**Comment by Marwin887** [comment]
> @Marwin887 по сетке с полигонами. Вот [ноутбук](https://github.com/NorthGateVologda/NorthGate/blob/main/Notebooks/Facility.ipynb)
> 
> Если тема с дубликатами решена, сейчас пересоздам и всё залью.

@olgapshen В Facility проблема с дубликатами решена

**Comment by olgapshen** [comment]
Так, ребята, у нас маленькая проблема, при открытии https://northgatevologda.ru/ система может переключится на [pgadmin.northgatevologda.ru](https://pgadmin.northgatevologda.ru/)
Добавить в начале поддомен нельзя, так как не сертификата, но нужно сказать оргам, что возможно нужно будет почистить кеш, и ещё, что у нас надо подтвердить ssl (принять риск и продолжить).

**Comment by olgapshen** [comment]
Ребята! Мы все молодцы.
@Marwin887 не забывай пожалуйста обновлять статус задач.

**Comment by olgapshen** [comment]
Архивирую задачу, если что задача тут:


![Image](https://github.com/NorthGateVologda/NorthGate/assets/13800244/b1f90a72-42a0-4cef-b6b4-02918cad9f7f)
