### ISSUE TITLE
Скорректировать таблицу с полигонами

### ISSUE THREAD

**Issue by Marwin887** [NorthGateVologda/NorthGate#43]
При проектировании дашборда понял, что не правильно сделали базу полигонов: facility_polygons,  facility_polygons_lens. 

**Проблемы:**

1 ) В талицах  facility_polygons,  facility_polygons_lens  id полигона у нас всегда уникальное, как и facility_id, при этом geometry у полигонов одинаковое. 

Из-за этого например Datalens визуализирует сетку состоящую из стопок полигонов. 

Невозможно рассчитать плотность населения в полигоне, дополнительная нагрузка на БД.

Пример для наглядности. 4 одинаковых полигона по координатам, но у всех разное ID

 ![Image](https://user-images.githubusercontent.com/136377502/257034025-176cc352-d73a-49b9-996d-df19e70c9491.png)

2) Часть полигонов "вылетает" за границы г. Архангельска (Попадают объекты в Новодвинске). Необходимо сделать отдельную сетку полигонов, не связанную с объектами и ограниченную полигоном города Архангельска (polygon_arxangelsk).  Т.е. центр полигона нужно брать не по объекту, это должна быть расчетная величина. 

3) Масштаб сетки очень маленький, сетка должна быть построена из расчета 500 м между центром полигона и его вершиной. (Согласно концепции 15 минутного города т.е. объекты должны быть в радиусе шаговой доступности).
Для сравнения синяя сетка, это текущая сетка, а зеленая ту что я построил в QGIS и скрин с яндекс карт 

![Image](https://user-images.githubusercontent.com/136377502/257034687-67f9a919-503a-4727-96b7-1dde7f884adc.png)

![Image](https://user-images.githubusercontent.com/136377502/257034697-82583dc4-60f5-4eed-af33-df2dfe8756df.png)

![Image](https://user-images.githubusercontent.com/136377502/257034700-511f84fc-d559-4d10-ad78-2393d55e46c1.png)

4) Сетка расположена под углом. На сетке не все полигоны.

Мне видится следующее решение проблемы:

1) Создать отдельную таблицу Polygon со столбцами Id_polygon и Geometry

2) Создать полигоны по центрам из таблицы
https://docs.google.com/spreadsheets/d/1dVta_ot99COWUScIVY2gK0kshjpBvVKykKbPvqoKWd4/edit?usp=sharing 
В таблице центра полигональной сетки, которую мне удалось создать в QGIS (она подходит по размерам и ограничена по г. Архангельску), но QGIS не умеет выводить данные в формате Polygon

![Image](https://user-images.githubusercontent.com/136377502/257035000-4daedddc-c487-4dfd-ab34-d1f453a63911.png)

3) Провести соотношение полученных полигонов и точек в таблицу facility, загрузить итоги в в таблицу facility в столбце Id_polygon (его нужно создать).

**Comment by Marwin887** [comment]
@olgapshen @sshiae @lvapl @Malaxov16  Ребят, если мы будем двигаться дальше по проекту (результаты будут 31 августа вечером), то сначала нужно решить вот эту проблему. А потом уже работь над фронтом. Прошу помочь.

**Comment by olgapshen** [comment]
> @olgapshen @sshiae @lvapl @Malaxov16 Ребят, если мы будем двигаться дальше по проекту (результаты будут 31 августа вечером), то сначала нужно решить вот эту проблему. А потом уже работь над фронтом. Прошу помочь.

Суперский анализ и постановка!!! Сегодня вечером погружусь в детали!!!

**Comment by olgapshen** [comment]
> 1 ) В талицах facility_polygons, facility_polygons_lens id полигона у нас всегда уникальное, как и facility_id, при этом geometry у полигонов одинаковое.

Это скорее всего баг в h3geo, но это в любом случае можно будет исправить, пройтись по всем полигонам, и удалить те, которые совмещаются на более чем 5% к примеру.

> Часть полигонов "вылетает" за границы г. Архангельска (Попадают объекты в Новодвинске). Необходимо сделать отдельную сетку полигонов, не связанную с объектами и ограниченную полигоном города Архангельска (polygon_arxangelsk). Т.е. центр полигона нужно брать не по объекту, это должна быть расчетная величина.

Это сделаю. Я так и хотела. Сначала делаем сетку в рамках города как в задаче с медучреждениями, затем слой центров квадратов, и уже по этим центрам делаем полигоны, далее удаляем дубликаты.

> Масштаб сетки очень маленький, сетка должна быть построена из расчета 500 м между центром полигона и его вершиной. (Согласно концепции 15 минутного города т.е. объекты должны быть в радиусе шаговой доступности).
Для сравнения синяя сетка, это текущая сетка, а зеленая ту что я построил в QGIS и скрин с яндекс карт

Это частично параметризируется, но для заданной величины, возможно придётся делать несколько сеток, а потом объединять.

> Сетка расположена под углом. На сетке не все полигоны.

По поводу угла надо конечно смотреть... скорее всего проблема в преобразовании между системами координат.

> Создать полигоны по центрам из таблицы
https://docs.google.com/spreadsheets/d/1dVta_ot99COWUScIVY2gK0kshjpBvVKykKbPvqoKWd4/edit?usp=sharing
В таблице центра полигональной сетки, которую мне удалось создать в QGIS (она подходит по размерам и ограничена по г. Архангельску), но QGIS не умеет выводить данные в формате Polygon

Вот расчёт этих центров надо как то автоматизировать, для выборки заданного города.

**Comment by olgapshen** [comment]
Так, беру эту задачу на себя.

**Comment by olgapshen** [comment]
Итак!!! Наконец то таблица с полигонами готова!!! `northgate.polygons_lens`

Сейчас заметила, что выше ты просил сделать большой радиус (от центра до вершины) в 500 метров, но до этого был разговор о 200, в общем я сделала 200. Вот так это выглядит в [DataLens](https://datalens.yandex.ru/wizard/41gzziyuue0it-polygons-lens-chart)

![Image](https://github.com/NorthGateVologda/NorthGate/assets/13800244/41115010-dd1c-48e8-ad40-8ce39a30d09b)

Сейчас закомичу Notebook.

**Comment by olgapshen** [comment]
Зацените алгоритм!!! https://github.com/NorthGateVologda/NorthGate/blob/main/Notebooks/Polygons.ipynb

**Comment by olgapshen** [comment]
Так! Надо теперь связующую таблицу сделать используя функции базы. Постараюсь сегодня сделать.

**Comment by Marwin887** [comment]
@olgapshen  @lvapl Оля, офигенно круто. Но нужно конечно сделать 500 метров, сейчас в один полигон попадает 1-3 больших дома максимум, из-за этого плотность населения по полигонах будет очень равномерная, либо с большими просадками, например там где в полигоне один ТРЦ. С парками еще сложнее фактически из-за того что парки большие они занимают всю площадь полигона.

**Comment by olgapshen** [comment]
@Marwin887 перезалила! Можно проверять.

**Comment by olgapshen** [comment]
Итак! Обогатила таблицу с полигонами WKT типами данных. Теперь осталось построить связующую таблицу.

![Image](https://github.com/NorthGateVologda/NorthGate/assets/13800244/8b504cf9-95da-4483-a954-872bccfbc113)

**Comment by olgapshen** [comment]
Построила связующую таблицу. Все скрипты тут: https://github.com/NorthGateVologda/NorthGateDBScripts/pulls
Пожалуйста пройдитесь завтра по PR-ам.
Связующая таблица называется: facility_polygons

Если что, вот скрипт на создание связующей таблицы, хотя он и так в PR-е в репозитории NorthGateDBScripts.

```
with a as (
	select
		f.facility_id f_id,
		p.id p_id
	from facility f
	inner join polygons_lens p
	on ST_contains(p.geometry, f.geometry)
)
insert into northgate.facility_polygons (
	facility_id,
	polygon_id
)
select f_id, p_id from a;

commit;
```
