### ISSUE TITLE
Написать User Story

### ISSUE THREAD

**Issue by olgapshen** [NorthGateVologda/NorthGate#5]
Написать `User Story` по нашему `MVP`. Тот самый минимум от авторизации до момента, что пользователь получит на экране точки оптимального расположения объектов.

Объединяю сюда следующие задачи:
* [Формализовать ФЗ](https://github.com/NorthGateVologda/NorthGate/issues/6)
* [Стейкхолдеры и методика](https://github.com/NorthGateVologda/NorthGate/issues/10)

Из задачи [Стейкхолдеры и методика](https://github.com/NorthGateVologda/NorthGate/issues/10) актуальны два последние пункта в одном из постов:

* Прогноз размещения "ПАРКОВ"(в проработке)...
Парк-земельный участок с естественной или специально посаженной [растительностью](https://ru.wikipedia.org/wiki/%D0%A0%D0%B0%D1%81%D1%82%D0%B8%D1%82%D0%B5%D0%BB%D1%8C%D0%BD%D0%BE%D1%81%D1%82%D1%8C), обустроенными [дорогами](https://ru.wikipedia.org/wiki/%D0%94%D0%BE%D1%80%D0%BE%D0%B3%D0%B0), [аллеями](https://ru.wikipedia.org/wiki/%D0%90%D0%BB%D0%BB%D0%B5%D1%8F), [водоёмами](https://ru.wikipedia.org/wiki/%D0%92%D0%BE%D0%B4%D0%BE%D1%91%D0%BC)[[1]](https://ru.wikipedia.org/wiki/%D0%9F%D0%B0%D1%80%D0%BA#cite_note-1), предназначенная для [отдыха](https://ru.wikipedia.org/wiki/%D0%9E%D1%82%D0%B4%D1%8B%D1%85) и прогулок открытая [озеленённая](https://ru.wikipedia.org/wiki/%D0%97%D0%B5%D0%BB%D1%91%D0%BD%D1%8B%D0%B5_%D0%BD%D0%B0%D1%81%D0%B0%D0%B6%D0%B4%D0%B5%D0%BD%D0%B8%D1%8F) [территория](https://ru.wikipedia.org/wiki/%D0%A2%D0%B5%D1%80%D1%80%D0%B8%D1%82%D0%BE%D1%80%D0%B8%D1%8F), с продуманным [ландшафтным](https://ru.wikipedia.org/wiki/%D0%9B%D0%B0%D0%BD%D0%B4%D1%88%D0%B0%D1%84%D1%82%D0%BD%D1%8B%D0%B9_%D0%B4%D0%B8%D0%B7%D0%B0%D0%B9%D0%BD) дизайном, подчиняющимся рельефу местности.
* Прогноз размещения объектов "Здравоохранения" (в проработке)....

**Comment by olgapshen** [comment]
Тут то у нас какой статус? :)

**Comment by olgapshen** [comment]
Обратите внимание, я обновила описание задачи.
Так же в связке у нас идут следующие задачи:

* [Реализовать API Backend-а](https://github.com/NorthGateVologda/NorthGateBackend/issues/14)
* [Сохранение пользовательских данных в базе](https://github.com/NorthGateVologda/NorthGateBackend/issues/15)
* [Реализовать frontend](https://github.com/NorthGateVologda/NorthGateWeb/issues/10)

**Comment by olgapshen** [comment]
[Ссылка](https://github.com/NorthGateVologda/NorthGateWiki/pull/2) на PR с диаграммой поведения frontend-а.

**Comment by olgapshen** [comment]
Ребята, @sshiae @lvapl @bagkir , тут будет думаю вестись основное обсуждение которое касается и backend-а и frontend-а и базы данных

**Comment by Marwin887** [comment]
![Image](https://github.com/NorthGateVologda/NorthGate/assets/136377502/d273ec24-4421-49ce-8264-fd86fc211997)

**Comment by Marwin887** [comment]
https://www.figma.com/file/KpPXNMQtbLjajls7ajMqTE/Untitled?type=design&node-id=0%3A1&mode=design&t=hPcwAEdnjPBYQofV-1

**Comment by olgapshen** [comment]
Давайте все макеты добавлять в [эту задачу](https://github.com/NorthGateVologda/NorthGateWeb/issues/2).
И кстати надо теперь прописать Figm-у в файл ресурсов. Сейчас пропишу.

**Comment by olgapshen** [comment]
![изображение](https://github.com/NorthGateVologda/NorthGate/assets/13800244/c0dff99e-4214-4219-9dc8-830f7bbe7405)

**Comment by Malaxov16** [comment]
@lvapl @sshiae @olgapshen написал User Story



[User Story.docx](https://github.com/NorthGateVologda/NorthGate/files/12064882/User.Story.docx)

**Comment by olgapshen** [comment]
1. Выбор населенного пункта для анализа.
        1.1. Пользователь вводит название населенного пункта
        1.2. Система в формате выпадающего списка предлагает подходящие под введенное название список населенных пунктов
        1.3. Пользователь выбирает нужный населенный пункт
        1.4. Система в области экрана с картой отображает населенный пункт, который полностью умещается в экран при максимально возможном масштабе.

Тогда нужно API переделать. Нужно создать новую функцию, которая будет брать часть имени НП и возвращать список. В списке кстати нужно указывать и область, так как НП с одним именем может быть в разных областях.

@Malaxov16 @Marwin887 можете актуализировать функции бекенда?
https://github.com/NorthGateVologda/NorthGateBackend/issues/14

**Comment by olgapshen** [comment]
Я думаю что очень крутое описание. Разве что нужно актуализировать API backend-а.
Я сейчас с Nifi буду возиться, это нужно для обогащения базы данными из Росреестра по плотности населения.
@sshiae @Malaxov16 @Marwin887 @lvapl кто нибудь может API актуализировать?
Я сейчас отдельную задачу поставлю.

**Comment by Malaxov16** [comment]
@olgapshen я думаю, сейчас в поиске населенного пункта можно ограничиться просто названием и не дополнять районом/поселением и т.д., если это трудозатратно, т.к. у нас пока только Архангельск.

**Comment by olgapshen** [comment]
> @olgapshen я думаю, сейчас в поиске населенного пункта можно ограничиться просто названием и не дополнять районом/поселением и т.д., если это трудозатратно, т.к. у нас пока только Архангельск.

Добавить область к пункту это не трудозатратно. В таблице и так есть эти данные.

**Comment by Marwin887** [comment]
> Я думаю что очень крутое описание. Разве что нужно актуализировать API backend-а. Я сейчас с Nifi буду возиться, это нужно для обогащения базы данными из Росреестра по плотности населения. @lvapl @Marwin887 @Malaxov16 @sshiae кто нибудь может API актуализировать? Я сейчас отдельную задачу поставлю.

@olgapshen я к сожалению никогда методы API не писал и имею только поверхностное представление @lvapl @Malaxov16 @sshiae ребят поможете?

**Comment by olgapshen** [comment]
> > Я думаю что очень крутое описание. Разве что нужно актуализировать API backend-а. Я сейчас с Nifi буду возиться, это нужно для обогащения базы данными из Росреестра по плотности населения. @lvapl @Marwin887 @Malaxov16 @sshiae кто нибудь может API актуализировать? Я сейчас отдельную задачу поставлю.
> 
> @olgapshen я к сожалению никогда методы API не писал и имею только поверхностное представление @lvapl @Malaxov16 @sshiae ребят поможете?

Понимаю :) Так то Тёма может их из User Story выцепить, а потом перед сдачей уже актуализируем документацию. Документация для презентации важна будет.

**Comment by Malaxov16** [comment]
> > > Я думаю что очень крутое описание. Разве что нужно актуализировать API backend-а. Я сейчас с Nifi буду возиться, это нужно для обогащения базы данными из Росреестра по плотности населения. @lvapl @Marwin887 @Malaxov16 @sshiae кто нибудь может API актуализировать? Я сейчас отдельную задачу поставлю.
> > 
> > @olgapshen я к сожалению никогда методы API не писал и имею только поверхностное представление @lvapl @Malaxov16 @sshiae ребят поможете?
> 
> Понимаю :) Так то Тёма может их из User Story выцепить, а потом перед сдачей уже актуализируем документацию. Документация для презентации важна 

Могу попробовать актуализировать API, но скорее всего только завтра( сегодня очень занят.

**Comment by olgapshen** [comment]
Думаю эту задачу можно перенести в завершённые. @Malaxov16 просил указывать время потребовавшиеся для решения, но этой информации у меня нет. Думаю Андрей укажет тут.
Предлагаю вести остальные дискуссии уже по ходу каждой отдельной задачи.
[User Story.docx](https://github.com/NorthGateVologda/NorthGate/files/12064882/User.Story.docx) я загрузила в Хранилище.
